(self.AMP=self.AMP||[]).push({n:"amp-iframe",v:"2009112034002",f:(function(AMP,_){
'use strict';var l,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function ba(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return}(function(){throw Error("Cannot find global object");})()}ba(this);"function"===typeof Symbol&&Symbol("x");var n;
if("function"==typeof Object.setPrototypeOf)n=Object.setPrototypeOf;else{var p;a:{var ca={a:!0},q={};try{q.__proto__=ca;p=q.a;break a}catch(a){}p=!1}n=p?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var r=n,u;function v(){return u?u:u=Promise.resolve(void 0)};function w(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var da=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;var y=self.AMP_CONFIG||{},ea=("string"==typeof y.cdnProxyRegex?new RegExp(y.cdnProxyRegex):y.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function fa(a){if(!self.document||!self.document.head||self.location&&ea.test(self.location.origin))return null;var b=self.document.head.querySelector('meta[name="'+a+'"]');return b&&b.getAttribute("content")||null}
var ha={thirdParty:y.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:y.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof y.thirdPartyFrameRegex?new RegExp(y.thirdPartyFrameRegex):y.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:y.cdnUrl||fa("runtime-host")||"https://cdn.ampproject.org",cdnProxyRegex:ea,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:y.errorReportingUrl||"https://us-central1-amp-error-reporting.cloudfunctions.net/r",betaErrorReporting:y.betaErrorReportingUrl||
"https://us-central1-amp-error-reporting.cloudfunctions.net/r-beta",localDev:y.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:y.geoApiUrl||fa("amp-geo-api")};self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var z=self.__AMP_LOG;function A(){if(!z.user)throw Error("failed to call initLogConstructor");return z.user}function B(){if(z.dev)return z.dev;throw Error("failed to call initLogConstructor");}function C(a,b,c,d,e){A().assert(a,b,c,d,e,void 0,void 0,void 0,void 0,void 0,void 0)};function D(a){return a||{}};var E;function ia(a,b){var c=a,d=b;var e=function(a){try{return d(a)}catch(h){throw self.__AMP_REPORT_ERROR(h),h;}};var f=ja();c.addEventListener("message",e,f?void 0:!1);return function(){c&&c.removeEventListener("message",e,f?void 0:!1);e=c=d=null}}function ja(){if(void 0!==E)return E;E=!1;try{var a={get capture(){E=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return E};function ka(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function la(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}function F(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};function ma(a,b){for(;a&&void 0!==a;a=a.parentElement)if(b(a))return a;return null}function na(a){return a.closest?a.closest(".i-amphtml-overlay"):ma(a,function(a){var b=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return b?b.call(a,".i-amphtml-overlay"):!1})};function oa(a,b){try{return JSON.parse(a)}catch(c){return b&&b(c),null}};function pa(a){if(!qa(a))return null;var b=a.indexOf("{");try{return JSON.parse(a.substr(b))}catch(c){return B().error("MESSAGING","Failed to parse message: "+a,c),null}}function qa(a){return"string"==typeof a&&0==a.indexOf("amp-")&&-1!=a.indexOf("{")};function ra(a,b){return ia(a,b)};function G(){this.T=100;this.I=this.M=0;this.w=Object.create(null)}G.prototype.has=function(a){return!!this.w[a]};G.prototype.get=function(a){var b=this.w[a];if(b)return b.access=++this.I,b.payload};G.prototype.put=function(a,b){this.has(a)||this.M++;this.w[a]={payload:b,access:this.I};if(!(this.M<=this.T)){B().warn("lru-cache","Trimming LRU cache");a=this.w;var c=this.I+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.M--)}};D({c:!0,v:!0,a:!0,ad:!0});var H,sa;
function ta(a){H||(H=self.document.createElement("a"),sa=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new G));var b=sa,c=H;if(b&&b.has(a))a=b.get(a);else{c.href=a;c.protocol||(c.href=c.href);var d={href:c.href,protocol:c.protocol,host:c.host,hostname:c.hostname,port:"0"==c.port?"":c.port,pathname:c.pathname,search:c.search,hash:c.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;d.origin=
c.origin&&"null"!=c.origin?c.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;b&&b.put(a,d);a=d}return a};function ua(a,b){for(var c=[],d=0,e=0;e<a.length;e++){var f=a[e];b(f,e,a)?c.push(f):(d<e&&(a[d]=f),d++)}d<a.length&&(a.length=d)};var I,va="Webkit webkit Moz moz ms O o".split(" ");function wa(a,b){var c=a.style;if(F("zIndex","--"))c="zIndex";else{I||(I=Object.create(null));var d=I.zIndex;if(!d){d="zIndex";if(void 0===c.zIndex){var e;b:{for(e=0;e<va.length;e++){var f=va[e]+"ZIndex";if(void 0!==c[f]){e=f;break b}}e=""}void 0!==c[e]&&(d=e)}I.zIndex=d}c=d}c&&(F(c,"--")?a.style.setProperty(c,b):a.style[c]=b)}function xa(a,b){void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};function ya(a,b,c){var d=a.listeningFors;!d&&c&&(d=a.listeningFors=Object.create(null));a=d||null;if(!a)return a;var e=a[b];!e&&c&&(e=a[b]=[]);return e||null}function za(a,b,c){var d=c?b.getAttribute("data-amp-3p-sentinel"):"amp";a=ya(a,d,!0);for(d=0;d<a.length;d++){var e=a[d];if(e.frame===b){var f=e;break}}f||(f={frame:b,events:Object.create(null)},a.push(f));return f.events}
function Aa(a){for(var b=D({sentinel:"unlisten"}),c=a.length-1;0<=c;c--){var d=a[c];if(!d.frame.contentWindow){a.splice(c,1);var e=d.events,f;for(f in e)e[f].splice(0,Infinity).forEach(function(a){a(b)})}}}
function Ba(a){a.listeningFors||a.addEventListener("message",function(b){if(b.data){var c=Ca(b.data);if(c&&c.sentinel){var d=b.source;var e=ya(a,c.sentinel);if(e){for(var f,k=0;k<e.length;k++){var h=e[k],m=h.frame.contentWindow;if(m){var g;if(!(g=d==m))b:{for(g=d;g&&g!=g.parent;g=g.parent)if(g==m){g=!0;break b}g=!1}if(g){f=h;break}}else setTimeout(Aa,0,e)}d=f?f.events:null}else d=e;var t=d;if(t){var x=t[c.type];if(x)for(x=x.slice(),d=0;d<x.length;d++)(0,x[d])(c,b.source,b.origin,b)}}}})}
function J(a,b,c,d,e,f){function k(b,d,k,h){if("amp"==b.sentinel){if(d!=a.contentWindow)return;var g="null"==k&&f;if(m!=k&&!g)return}if(e||d==a.contentWindow)"unlisten"==b.sentinel?t():c(b,d,k,h)}var h=a.ownerDocument.defaultView;Ba(h);d=za(h,a,d);var m=ta(a.src).origin,g=d[b]||(d[b]=[]),t;g.push(k);return t=function(){if(k){var a=g.indexOf(k);-1<a&&g.splice(a,1);c=g=k=null}}}
function Da(a,b,c,d,e){if(a.contentWindow)for(d.type=c,d.sentinel=e?a.getAttribute("data-amp-3p-sentinel"):"amp",a=d,e&&(a="amp-"+JSON.stringify(d)),d=0;d<b.length;d++)e=b[d],e.win.postMessage(a,e.origin)}function Ca(a){"string"==typeof a&&(a="{"==a.charAt(0)?oa(a,function(a){B().warn("IFRAME-HELPER","Postmessage could not be parsed. Is it in a valid JSON format?",a)})||null:qa(a)?pa(a):null);return a}
function K(a,b){var c=this;this.h=a;this.K=!1;this.m=[];this.U=J(this.h,"send-intersections",function(a,e,f){c.m.some(function(a){return a.win==e})||c.m.push({win:e,origin:f});b(a,e,f)},this.K,this.K)}K.prototype.send=function(a,b){ua(this.m,function(a){return!a.win.parent});Da(this.h,this.m,a,b,this.K)};K.prototype.destroy=function(){this.U();this.m.length=0};var L=[[300,250],[320,50],[300,50],[320,100]];
function Ea(a){var b=(a.getAttribute("allow")||"").trim();a.setAttribute("allow","execution-while-not-rendered 'none';"+b)};function Fa(a,b,c){if(!(0==b&&0==c||0==a.width&&0==a.height)){b=a.left+b;c=a.top+c;var d=a.width;a=a.height;a={left:b,top:c,width:d,height:a,bottom:c+a,right:b+d,x:b,y:c}}return a};var Ga=[0,.05,.1,.15,.2,.25,.3,.35,.4,.45,.5,.55,.6,.65,.7,.75,.8,.85,.9,.95,1];Date.now();function Ha(a,b){var c=this;this.S=a;this.C=null;this.N=new K(b,function(){c.C.observe(c.S.element)});this.C=new IntersectionObserver(function(a){c.N.send("intersection",D({changes:a.map(Ia)}))},{threshold:Ga})}Ha.prototype.destroy=function(){this.C.disconnect();this.C=null;this.N.destroy();this.N=null};
function Ia(a){return{time:a.time,rootBounds:a.rootBounds,boundingClientRect:a.boundingClientRect,intersectionRect:a.intersectionRect,intersectionRatio:a.intersectionRatio}};function M(a){if(a.__AMP__EXPERIMENT_TOGGLES)return a.__AMP__EXPERIMENT_TOGGLES;a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);var b=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var c in a.AMP_CONFIG){var d=a.AMP_CONFIG[c];"number"===typeof d&&0<=d&&1>=d&&(b[c]=Math.random()<d)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length){var e=a.AMP_CONFIG["allow-doc-opt-in"],f=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]');
if(f){var k=f.getAttribute("content").split(",");for(c=0;c<k.length;c++)-1!=e.indexOf(k[c])&&(b[k[c]]=!0)}}Object.assign(b,Ja(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length){c=a.AMP_CONFIG["allow-url-opt-in"];var h=a.location.originalHash||a.location.hash;a=Object.create(null);if(h)for(var m;m=da.exec(h);){var g=w(m[1],m[1]);m=m[2]?w(m[2].replace(/\+/g," "),m[2]):"";a[g]=m}for(h=0;h<c.length;h++)g=a["e-"+c[h]],"1"==g&&(b[c[h]]=!0),"0"==
g&&(b[c[h]]=!1)}return b}function Ja(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(e){B().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var c=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var d=0;d<c.length;d++)0!=c[d].length&&("-"==c[d][0]?a[c[d].substr(1)]=!1:a[c[d]]=!0);return a};function N(a,b){var c=a.ownerDocument.defaultView,d=c.__AMP_TOP||(c.__AMP_TOP=c),e=c!=d,f=!!M(d)["ampdoc-fie"];e&&!f?b=O(c,b)?P(c,b):null:(a=Q(a),a=R(a),b=O(a,b)?P(a,b):null);return b}function S(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return P(a,b)}function Q(a){return a.nodeType?S((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function R(a){a=Q(a);return a.isSingleDoc()?a.win:a}
function P(a,b){O(a,b);a=T(a)[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function Ka(a){var b=T(a).consentPolicyManager;if(b){if(b.promise)return b.promise;P(a,"consentPolicyManager");return b.promise=Promise.resolve(b.obj)}return null}function T(a){var b=a.__AMP_SERVICES;b||(b=a.__AMP_SERVICES={});return b}function O(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)}
function La(){var a=new ka,b=a.promise,c=a.resolve;a=a.reject;b.catch(function(){});return{obj:null,promise:b,resolve:c,reject:a,context:null,ctor:null}};function U(a){var b=Ka(R(a));if(b)return b;var c=Q(a);return c.waitForBodyOpen().then(function(){var a=c.win;var b=c.win.document.head;if(b){var f={};b=b.querySelectorAll("script[custom-element],script[custom-template]");for(var k=0;k<b.length;k++){var h=b[k];h=h.getAttribute("custom-element")||h.getAttribute("custom-template");f[h]=!0}f=Object.keys(f)}else f=[];return f.includes("amp-consent")?S(a,"extensions").waitForExtension(a,"amp-consent"):v()}).then(function(){var b=c.win;if(b.__AMP_EXTENDED_ELEMENTS&&
b.__AMP_EXTENDED_ELEMENTS["amp-consent"]){b=R(a);var e=Ka(b);e?b=e:(b=T(b),b.consentPolicyManager=La(),b=b.consentPolicyManager.promise)}else b=null;return b})};function Ma(a,b){b=void 0===b?"default":b;return U(a).then(function(a){return a?a.whenPolicyResolved(b):null})}function Na(a,b){return U(a).then(function(a){return a?a.getConsentStringInfo(b):null})}function Oa(a,b){return U(a).then(function(a){return a?a.getConsentMetadataInfo(b):null})};var Pa={"AMP-FX-FLYING-CARPET":!0,"AMP-LIGHTBOX":!0,"AMP-STICKY-AD":!0,"AMP-LIGHTBOX-GALLERY":!0};var Qa="allowfullscreen allowpaymentrequest allowtransparency allow frameborder referrerpolicy scrolling tabindex title".split(" "),Ra=0;function V(a){a=AMP.BaseElement.call(this,a)||this;a.G=null;a.D=!1;a.L=!1;a.o=!1;a.R=!1;a.J=null;a.h=null;a.F=!1;a.B=null;a.l="";a.H=null;a.iframeSrc=null;a.A=null;a.j=null;a.P=!1;return a}var W=AMP.BaseElement;V.prototype=aa(W.prototype);V.prototype.constructor=V;
if(r)r(V,W);else for(var X in W)if("prototype"!=X)if(Object.defineProperties){var Sa=Object.getOwnPropertyDescriptor(W,X);Sa&&Object.defineProperty(V,X,Sa)}else V[X]=W[X];V.W=W.prototype;l=V.prototype;l.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a||"fluid"==a||"intrinsic"==a};
function Ta(a,b,c){var d=window.location.href;c=void 0===c?"":c;a=a.element;var e=N(a,"url"),f=e.parse(b),k=f.hostname,h=f.protocol;f=f.origin;C(e.isSecure(b)||"data:"==h,"Invalid <amp-iframe> src. Must start with https://. Found %s",a);var m=e.parse(d);C(!/\sallow-same-origin\s/i.test(" "+c+" ")||f!=m.origin&&"data:"!=h,"Origin of <amp-iframe> must not be equal to container %sif allow-same-origin is set. See https://github.com/ampproject/amphtml/blob/master/spec/amp-iframe-origin-policy.md for details.",
a);C(!(la(k,"."+ha.thirdPartyFrameHost)||la(k,".ampproject.org")),"amp-iframe does not allow embedding of frames from ampproject.*: %s",b);return b}
function Ua(a){var b=a.element.getLayoutBox(),c=Math.min(600,.75*a.getViewport().getSize().height);C(b.top>=c,"<amp-iframe> elements must be positioned outside the first 75% of the viewport or 600px from the top (whichever is smaller): %s  Current position %s. Min: %sPositioning rules don't apply for iframes that use `placeholder`.See https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md#iframe-with-placeholder for details.",a.element,b.top,c)}
function Va(a,b){if(b){a=N(a.element,"url").parse(b);var c=a.hash;"data:"==a.protocol||c&&"#"!=c||(a=b.indexOf("#"),b=(-1==a?b:b.substring(0,a))+"#amp=1");return b}}
l.firstAttachedCallback=function(){this.l=this.element.getAttribute("sandbox");var a;if(!(a=Va(this,this.element.getAttribute("src"))))if(a=this.element.getAttribute("srcdoc")){C(!(" "+this.l+" ").match(/\s+allow-same-origin\s+/i),"allow-same-origin is not allowed with the srcdoc attribute %s.",this.element);if("undefined"!==typeof TextEncoder)var b=(new TextEncoder("utf-8")).encode(a);else{a=unescape(encodeURIComponent(a));b=new Uint8Array(a.length);for(var c=0;c<a.length;c++){var d=a.charCodeAt(c);
b[c]=d}}a=btoa;c=Array(b.length);for(d=0;d<b.length;d++)c[d]=String.fromCharCode(b[d]);b=c.join("");a="data:text/html;charset=utf-8;base64,"+a(b)}else a=void 0;this.iframeSrc=Ta(this,a,this.l)};l.preconnectCallback=function(a){this.iframeSrc&&S(this.win,"preconnect").url(this.getAmpDoc(),this.iframeSrc,a)};
l.buildCallback=function(){this.G=this.getPlaceholder();this.D=!!this.G;(this.F=this.element.hasAttribute("resizable"))&&this.element.setAttribute("scrolling","no");this.element.hasAttribute("frameborder")||this.element.setAttribute("frameborder","0");var a=this.element;if("no"!=a.getAttribute("scrolling")){var b=a.ownerDocument.createElement("i-amphtml-scroll-container");a.appendChild(b);a=b}this.A=a;Wa(this)};
l.onLayoutMeasure=function(){Xa(this);var a=this.element;a:{var b=a.getLayoutBox();var c=b.height;b=b.width;for(var d=0;d<L.length;d++){var e=L[d][0],f=L[d][1];if(!(f>c||e>b)&&20>=c-f&&20>=b-e){c=!0;break a}}c=!1}this.L=c;c=this.element;b=c.getLayoutBox();this.o=10<b.width||10<b.height?!1:!na(c);if(c=this.L){c=this.win;b=!1;d=0;do Pa[a.tagName]?(d++,b=!1):(e=(c.getComputedStyle(a)||Object.create(null)).position,"fixed"!=e&&"sticky"!=e||(b=!0)),a=a.parentElement;while(a&&"BODY"!=a.tagName);c=!(!b&&
1>=d)}this.R=c};function Xa(a){if(a.h){var b=a.getViewport().getLayoutRect(a.h),c=a.getLayoutBox();a.J=Fa(b,-c.left,-c.top)}}l.getIntersectionElementLayoutBox=function(){if(!this.h)return AMP.BaseElement.prototype.getIntersectionElementLayoutBox.call(this);var a=this.getLayoutBox();this.J||Xa(this);return Fa(this.J,a.left,a.top)};
l.layoutCallback=function(){var a=this;C(!this.R,"amp-iframe is not used for displaying fixed ad. Please use amp-sticky-ad and amp-ad instead.");this.D||Ua(this);this.F&&C(this.getOverflowElement(),"Overflow element must be defined for resizable frames: %s",this.element);if(!this.iframeSrc)return v();if(this.o&&!this.getAmpDoc().registerSingleton(1))return console.error("Only 1 analytics/tracking iframe allowed per page. Please use amp-analytics instead or file a GitHub issue for your use case: https://github.com/ampproject/amphtml/issues/new"),
v();var b=this.element.ownerDocument.createElement("iframe");this.h=b;this.applyFillContent(b);b.name="amp_iframe"+Ra++;this.D&&wa(b,-1);this.propagateAttributes(Qa,b);var c=b.getAttribute("allow")||"";c=c.replace("autoplay","autoplay-disabled");b.setAttribute("allow",c);b.setAttribute("sandbox",this.l||"");M(this.win)["pausable-iframe"]&&Ea(this.h);b.src=this.iframeSrc;this.o||(this.B=new Ha(this,b));b.onload=function(){b.readyState="complete";a.O();a.o&&(a.iframeSrc=null,S(a.win,"timer").promise(5E3).then(function(){b.parentElement&&
b.parentElement.removeChild(b);a.element.setAttribute("amp-removed","");a.h=null}))};J(b,"embed-size",function(b){Y(a,b.height,b.width)},void 0,void 0,!0);this.H=ra(this.win,function(b){if(a.h&&b.source===a.h.contentWindow&&(b=b.data,"string"===typeof b&&F(b,"pym"))){var c=b.split(/xPYMx/);"height"===c[2]?Y(a,parseInt(c[3],10),void 0):"width"===c[2]?Y(a,void 0,parseInt(c[3],10)):A().warn("amp-iframe","Unsupported Pym.js message: "+b)}});this.D&&J(b,"embed-ready",this.O.bind(this));J(b,"send-consent-data",
function(b,c,f){Ya(a,c,f)});this.A.appendChild(b);return this.loadPromise(b).then(function(){a.A!=a.element&&S(a.win,"timer").delay(function(){a.mutateElement(function(){a.A.classList.add("amp-active")})},1E3)})};function Ya(a,b,c){var d=AMP.BaseElement.prototype.getConsentPolicy.call(a)||"default",e=Za(a,d),f=$a(a,d),k=ab(a,d);Promise.all([f,e,k]).then(function(a){var d=D({sentinel:"amp",type:"consent-data",consentMetadata:a[0],consentString:a[1],consentPolicyState:a[2]});b.postMessage(d,c)})}
function Za(a,b){return Na(a.element,void 0===b?"default":b)}function $a(a,b){return Oa(a.element,void 0===b?"default":b)}function ab(a,b){return Ma(a.element,void 0===b?"default":b)}l.unlayoutOnPause=function(){return!Z(this)};l.pauseCallback=function(){Z(this)&&xa(this.h,!1)};l.resumeCallback=function(){Z(this)&&xa(this.h,!0)};
function Z(a){var b;if(b=!!M(a.win)["pausable-iframe"]&&!!a.h)a=a.h,b=!!a.featurePolicy&&-1!=a.featurePolicy.features().indexOf("execution-while-not-rendered")&&!a.featurePolicy.allowsFeature("execution-while-not-rendered");return b}l.unlayoutCallback=function(){this.H&&(this.H(),this.H=null);if(this.h){var a=this.h;a.parentElement&&a.parentElement.removeChild(a);this.G&&this.togglePlaceholder(!0);this.h=null;this.B&&(this.B.destroy(),this.B=null)}return!0};
l.getLayoutPriority=function(){return this.L?2:this.o?1:AMP.BaseElement.prototype.getLayoutPriority.call(this)};l.mutatedAttributesCallback=function(a){var b=a.src;void 0!==b&&(this.iframeSrc=Va(this,b),this.h&&(this.h.src=Ta(this,this.iframeSrc,this.l)));this.h&&a.title&&this.propagateAttributes(["title"],this.h)};l.O=function(){var a=this;this.G&&this.getVsync().mutate(function(){a.h&&(wa(a.h,0),a.togglePlaceholder(!1))})};l.firstLayoutCompleted=function(){};
l.throwIfCannotNavigate=function(){if(!/\sallow-top-navigation\s/i.test(" "+this.l+" "))throw A().createError('"AMP.navigateTo" is only allowed on <amp-iframe> when its "sandbox" attribute contains "allow-top-navigation".');};
function Y(a,b,c){if(a.F)if(100>b)a.user().error("amp-iframe","Ignoring embed-size request because the resize height is less than 100px. If you are using amp-iframe to display ads, consider using amp-ad instead.",a.element);else{var d,e;b=parseInt(b,10);isNaN(b)||(d=Math.max(b+(a.element.offsetHeight-a.h.offsetHeight),b));c=parseInt(c,10);isNaN(c)||(e=Math.max(c+(a.element.offsetWidth-a.h.offsetWidth),c));void 0!==d||void 0!==e?a.attemptChangeSize(d,e).then(function(){void 0!==d&&a.element.setAttribute("height",
d);void 0!==e&&a.element.setAttribute("width",e)},function(){}):a.user().error("amp-iframe","Ignoring embed-size request because no width or height value is provided",a.element)}else a.P||(a.user().error("amp-iframe","Ignoring embed-size request because this iframe is not resizable",a.element),a.P=!0)}
function Wa(a){if(M(a.win)["iframe-messaging"]){var b=a.element,c=b.getAttribute("src");c&&(a.j=N(b,"url").parse(c).origin);a.registerAction("postMessage",function(b){a.j?a.h.contentWindow.postMessage(b.args,a.j):A().error("amp-iframe",'"postMessage" action is only allowed with "src"attribute with an origin.')});if(a.j){var d=0,e=function(b){if(b.source===a.h.contentWindow)if(b.origin!==a.j)A().error("amp-iframe",'"message" received from unexpected origin: '+b.origin+". Only allowed from: "+a.j);
else{if(a.getAmpDoc().getRootNode().activeElement!==a.h)var c=!1;else c=a.win.document.createElement("audio"),c.play(),c=c.paused?!1:!0;if(c){var f=b.data;try{var m=JSON.parse(JSON.stringify(f))}catch(t){A().error("amp-iframe",'Data from "message" event must be JSON.');return}var g=a.win;b=D({data:m});c={detail:b};Object.assign(c,void 0);"function"==typeof g.CustomEvent?b=new g.CustomEvent("amp-iframe:message",c):(g=g.document.createEvent("CustomEvent"),g.initCustomEvent("amp-iframe:message",!!c.bubbles,
!!c.cancelable,b),b=g);N(a.element,"action").trigger(a.element,"message",b,3)}else d++,A().error("amp-iframe",'"message" event may only be triggered from a user gesture.'),10<=d&&(A().error("amp-iframe",'Too many non-gesture-triggered "message" events; detaching event listener.'),a.win.removeEventListener("message",e))}};a.win.addEventListener("message",e)}}}l.V=function(a){this.j=a};(function(a){a.registerElement("amp-iframe",V)})(self.AMP);
})});

//# sourceMappingURL=amp-iframe-0.1.js.map
